### ISSUE TITLE
Refactor index.js

### ISSUE THREAD

**Issue by bradreeder** [CYPIAPT-LNDSE/welcome-to-camhs#113]
The team has requested any time you're free @MHemsley @des-des if you'd be able to review the index.js file with an eye to refactoring it to avoid repetition.

**Comment by des-des** [comment]
I do not think this file needs refactoring. We could make it more dry, but I think you would add complexity and lose clarity, without gaining much.

I big problem in this file is naming.
eg `addKeyupEvent` is actually putting something in local storage, and does not get given a function to call on keyup.

If you go through this file and think hard about names, I would be happy to have another look, as there might be an obvious abstraction that stands out clearer with nice naming..

@RhodesPeter @skibinska what do you think?
