### ISSUE TITLE
Sprint 2 planning

### ISSUE THREAD

**Issue by bradreeder** [CYPIAPT-LNDSE/welcome-to-camhs#114]
@RhodesPeter & @skibinska would like to get started on the second sprint as soon as possible. 

We'll be speaking with @Jasminpatel1 about arranging dates for user-testing tomorrow. However, as there is still functionality and bugs to work on that don't necessitate user-feedback, I'd suggest starting with a sprint-planning session on Tuesday morning and then reviewing mid-sprint what needs to be adapted in light of the user feedback.

@MHemsley @nogainbar @des-des @Jasminpatel1  Would you be free for sprint-planning at 10am Tuesday?

**Comment by nogainbar** [comment]
Yes I will be free for that. :) 👍

**Comment by des-des** [comment]
@bradreeder I was not planning on being present for the sprint planning session. I hope that is okay.

I would be happy to cast my eye over some time estimates if you, @RhodesPeter and @skibinska would appreciate that.

**Comment by MHemsley** [comment]
I am free, is there a hangouts link?

**Comment by RhodesPeter** [comment]
I am closing this issue as the sprint 2 planning has taken place and sprint 2 is coming to an end.
