### ISSUE TITLE
CYP IAPT Young Advisors Feedback

### ISSUE THREAD

**Issue by amgoforth** [CYPIAPT-LNDSE/welcome-to-camhs#117]
•         How many Fruit or veg are you eating section: this needs to be made more clear that when moving up the tree, the number is increasing. Add numbers to this part
•         How are you feeling section: It is not clear what to do in this section. Why is the banana there?
•         What are you interested in section: can users have the option to write their own interests in? Or at least have a free text ‘other’ box? Some of the options might be of no interest to the users 
•         What do you like and dislike about your friendships? This wording is confusing – should it be separated out to like and dislike? Is there a need to have dislike? It seems strange seeing it paired next to the word friendship.

**Comment by RhodesPeter** [comment]
Thank you @amgoforth 😀

**Comment by Jasminpatel1** [comment]
Thanks Alex, I received similar feedback but from different people. What age group gave you this feedback?

**Comment by amgoforth** [comment]
Between 18-23 so not your demographic.

**Comment by RhodesPeter** [comment]
I am closing this issue as we have have addressed the points highlighted.
