### ISSUE TITLE
Add verification to email page to say email has been sent.

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#126]
We need a way to tell the user that their email has been sent.

**Comment by Jasminpatel1** [comment]
Hi Peter, please add a final page which says the email has been sent. On the same page include:  "Please send feedback or suggestions to jasminpatel@live.co.uk".
At the bottom of the page include: "Jasmin patel, product Owner, Peter Rhodes and Ewelina Skibinska, Developers. Acknowldgements to children who gave their viwes, Barnet Child and Adolescent Mental Healh Service, CYP-IAPT, Founders & Coders.

**Comment by RhodesPeter** [comment]
Thanks @Jasminpatel1. We will find a way to add this information 😀
