### ISSUE TITLE
Feedback from Exec Meeting

### ISSUE THREAD

**Issue by CharlotteBarrett** [CYPIAPT-LNDSE/welcome-to-camhs#145]
HI All,

Alex demoed the Grow and WtC apps in the CYP IAPT exec meeting yesterday and collected feedback about the products. The feedback received for the 'WtC' is outlined below:

- Loved the concept of popping the balloons, but suggest this is inverted so that young people pop the non-applicable balloons, leaving the balloons that best describe them.
-  'Select Activities that you like doing' section: suggestion that this wording is too sophisticated for target user. Can the activities either be changed to something simpler like 'playing' 'sleeping' etc, or can there be the the option to write your own activities.
-Group felt that 'Welcome to CAMHS' is a misleading title for what is actually included in the app. Suggestions to change title to something like 'Things I might get asked at CAMHS', so that it acts as a discussion prompt for parents to bring up the concept of CAMHS, prepares the child and gives families the opportunity to use the app before their first visit. 
- Suggest moving the first question 'how many fruit...' to later in the form; this is asking about eating fruit which is often a bone of contention for young people and might put them off completing the form. 
- OVerall: the app looks great and is appealing, but the language throughout is too sophisticated and would benefit from being adapted to a  younger audience.

**Comment by RhodesPeter** [comment]
Thank you @CharlotteBarrett :)

**Comment by RhodesPeter** [comment]
I am closing this issue as we have incorporated these suggestions where possible in sprint 2.
