### ISSUE TITLE
Move repo to CYP-IAPT organisation

### ISSUE THREAD

**Issue by MHemsley** [CYPIAPT-LNDSE/welcome-to-camhs#15]
Nominate someone to be added to the organisation repo as admin and to move the repo to there

**Comment by RhodesPeter** [comment]
Hello, please can you add rhodespeter@hotmail.co.uk to the organisation repo and I will move the project over to you.

**Comment by RhodesPeter** [comment]
Hi, we have transferred this repo to CYP-IAPT, please could you close this issue?

**Comment by MHemsley** [comment]
Thanks @RhodesPeter Issue closes
