### ISSUE TITLE
Inspirations

### ISSUE THREAD

**Issue by skibinska** [CYPIAPT-LNDSE/welcome-to-camhs#16]

**Comment by skibinska** [comment]
we can style like button above our personality buttons #10 
![personality-button](https://cloud.githubusercontent.com/assets/10700103/22427228/3a28b2ee-e6fa-11e6-8eab-aa812de20d5b.png)

**Comment by RhodesPeter** [comment]
![screen shot 2017-01-30 at 14 44 13](https://cloud.githubusercontent.com/assets/18164707/22427354/c2b1a620-e6fa-11e6-80be-db5eb4fc7344.png)

It is fairly easy to create colourful and scalable drawings like this. I think these colours and boldness would work well for our project.

**Comment by skibinska** [comment]
very nice [svg animations](https://tympanus.net/Tutorials/AnimatedAnimals/index.html)

**Comment by RhodesPeter** [comment]
I am closing this issue as it is no longer needed.
