### ISSUE TITLE
Choose the palette

### ISSUE THREAD

**Issue by skibinska** [CYPIAPT-LNDSE/welcome-to-camhs#19]

**Comment by RhodesPeter** [comment]
How do people feel about this colour palette?
![colour-palette](https://cloud.githubusercontent.com/assets/18164707/22432840/374ce982-e70e-11e6-96d7-b8a3d478820c.jpg)

[colour-palette.pdf](https://github.com/CYPIAPT-LNDSE/welcome-to-camhs/files/739659/colour-palette.pdf)

**Comment by RhodesPeter** [comment]
I am closing this issue as we have agreed on the colour palette above and created this app using these colours as a guide.
