### ISSUE TITLE
Choose the fonts

### ISSUE THREAD

**Issue by skibinska** [CYPIAPT-LNDSE/welcome-to-camhs#20]

**Comment by RhodesPeter** [comment]
I like these ones:

For the body:
https://fonts.google.com/specimen/Nunito
https://fonts.google.com/specimen/Varela+Round

For headers - to use sparingly:
https://fonts.google.com/specimen/Courgette
https://fonts.google.com/specimen/Carter+One

**Comment by RhodesPeter** [comment]
I am closing this issue as we have chosen and implemented these two fonts:

- https://fonts.google.com/specimen/Montserrat
- https://fonts.google.com/specimen/Henny+Penny
