### ISSUE TITLE
Update for Jasmine

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#29]
Hey Jasmine,

Here are some of the pages we made today. Everything is very much still in the process of being created so feel free to make suggestions and let us know what you think.

![screen shot 2017-01-31 at 19 06 17](https://cloud.githubusercontent.com/assets/18164707/22480230/a38bd448-e7e8-11e6-9914-6e59029b7a74.png)
![screen shot 2017-01-31 at 19 06 28](https://cloud.githubusercontent.com/assets/18164707/22480232/a397140c-e7e8-11e6-8ed1-793a8ed48a70.png)
![screen shot 2017-01-31 at 19 06 38](https://cloud.githubusercontent.com/assets/18164707/22480231/a3960d14-e7e8-11e6-8f2f-0f7f6b1f593b.png)

**Comment by RhodesPeter** [comment]
Here are a couple of the pages we were working on today. The food page and personality pages are nearly finished but not quite.

![screen shot 2017-02-01 at 18 33 28](https://cloud.githubusercontent.com/assets/18164707/22520695/46d62db4-e8ad-11e6-84f2-d9088c143357.png)
![screen shot 2017-02-01 at 18 33 38](https://cloud.githubusercontent.com/assets/18164707/22520697/48735138-e8ad-11e6-9f33-5e5fbe456fee.png)

**Comment by Jasminpatel1** [comment]
Nice!

**Comment by RhodesPeter** [comment]
I am closing this issue as it relates to the prototype and initial pitching stage of the project. Jasmin has the link to the website hosted on Heroku which will always hold the latest version of the project.
