### ISSUE TITLE
Jasmine to accept invitation to become a collaborator. 

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#3]
Hey Jasmin, 

Please can you accept an invitation to become a collaborator on this project. You should have an email from GitHub that was sent on Saturday (it might be in your junk box).

If you have any problems you can leave a comment on this issue and we will be around to help you out.

**Comment by Jasminpatel1** [comment]
Thanks Peter.
I've just been looking through all the issues/comments, it's all very exciting! 
I have put together a rough template of ideas and basic images of what the App could look like. It’s on Microsoft Word so was just wondering how I can send this across to you and Ewelina for your thoughts.

**Comment by RhodesPeter** [comment]
Hi @Jasminpatel1 thank you for looking over everything, I hope you have not found it too overwhelming. I think you can drag the word document into a comment in an issue (where we are writing now) and we will be able to download it. You can definitely do this with a PDF.

**Comment by Jasminpatel1** [comment]
Thanks, I'm next in the office tomorrow so will send it over to you then. By the way do you have the timelines of when the prototype is going to be finished by? I have lots to share with you both

**Comment by Jasminpatel1** [comment]
Hi Peter, I'll send this across shortly, hopefully by tomorrow. Just to double check when is the deadline for the MVP to be completed by? I have quite a few ideas to share!! Is this the best method of communication?

**Comment by bradreeder** [comment]
@Jasminpatel1 We'll be finishing the prototype at the end of Thursday, so if you have ideas you'd like to be implemented tomorrow & thursday then sharing it here by early tomorrow would be ideal.

We'll be having a morning-standup meeting some time between 10-10:30am tomorrow, in which we discuss our current progress & plans for the day. If you're able to join us remotely we could chat with you then as well?

**Comment by Jasminpatel1** [comment]
Hi, this looks good and seems very appropriate for the younger kids. I attach my draft version of the App, this is what I envisaged it to look like and I wonder if it is more suited for children aged 7/8 years old up to 12 years? Let me know what you both think and what is possible in the time frame.

**Comment by Jasminpatel1** [comment]
I tried attaching the pdf here, also tried dragging and dopping but it doesn't work. I will try again tomorrow.

**Comment by RhodesPeter** [comment]
Thanks Jasmine, I am happy for you to email it to me at rhodespeter@hotmail.co.uk

**Comment by Jasminpatel1** [comment]
Thanks Peter, I think it will work now as I have changed the web browser. Please let me know if the attachment comes through.
 
[Welcome to CAMHS App-Jasmin Patel Jan 2016.pdf](https://github.com/CYPIAPT-LNDSE/welcome-to-camhs/files/744009/Welcome.to.CAMHS.App-Jasmin.Patel.Jan.2016.pdf)

**Comment by RhodesPeter** [comment]
Hello Jasmine, thank you for the pdf. 

If you are free to chat at any time today via phone call that would be great and we will be here until 6pm. This may be the most efficient way to get a clear idea of what you would like design wise. 

In response to the tweaking of the app to fit more inline with what you feel is appropriate for 8 - 12 year olds, we have had a chat with Bradley and have come up with a plan. We're confident that we can do this but not in time for the pitches to Anna Freud tomorrow. We are going to create the 3 more pages today in the same style so that we can present a solid and cohesive product, next week when you test the product on the age range we should be able to get some clear feedback from the young people about their thoughts on the style and if they think it is suitable for them. If we win the contract we would be able to easily take this feedback and create imagery that is most appropriate. 

Does this sound ok?

**Comment by Jasminpatel1** [comment]
Hi Peter, thats sounds great. 
I can call you now if you would like, wha number are you on?

**Comment by RhodesPeter** [comment]
Hi Jasmin my number is 07833798916 (note-to-self, delete my number from here later)

**Comment by RhodesPeter** [comment]
Hi Jasmin, are you free tomorrow evening from 5.30pm-7.20pm to re-pitch your product using the prototype that Ewelina and I are creating? Sorry for asking you so late notice. I believe that you will have the prototype to test/run past some young people next week, but you won't be expected to present again after tomorrow.

**Comment by bradreeder** [comment]
@RhodesPeter @Jasminpatel1 my understanding is that we'll be presenting the prototypes tomorrow and that you'll need to prepare your presentation for a separate evening next Thursday. Apologies for any confusion if I'm mistaken, I was out of office when Peter spoke to you earlier.

@MHemsley @CYPIAPT-admin Could you confirm if this is correct?

**Comment by Jasminpatel1** [comment]
Hi, thank you. that's great! see you all tomorrow.

**Comment by RhodesPeter** [comment]
We have an update from Alex:

Dear All,

A reminder that tomorrow evening (Thursday 2nd February from 5:30pm) the working prototypes will be presented to the group of product owners and developers at a Prototype Handover event.
Food and refreshments will be available from 5:30pm and each of the six teams will have 10mins to present their app. The session will close soon after 7pm.

The purpose of the event is to handover the apps to product owners and for the whole group to see the apps so far.

Product owners will be then be gathering feedback over the next week, in preparation for the Pitch event on 9th February (5:30pm onwards, as for the Prototype Handover) by their product owners and developers for a panel to choose which 2 apps will be developed further.

**Comment by RhodesPeter** [comment]
I am closing this issue as it refers to the prototype. We will raise new issues for the MVP.
