### ISSUE TITLE
Provide link for prototype show and tell

### ISSUE THREAD

**Issue by MHemsley** [CYPIAPT-LNDSE/welcome-to-camhs#44]
Hi,

I haven't looked through the issues or commits, but couldn't see and obvious link to a deployment,
can you provide ASAP as we're setting up.

M

**Comment by RhodesPeter** [comment]
Hi @MHemsley! Sorry we spotted this issue too late. We will send the link over to you when it's online, this shouldn't take too long. Sorry I also didn't realise earlier that I could have just plugged my laptop in for the presentation 😳

**Comment by RhodesPeter** [comment]
https://cypiapt-lndse.github.io/welcome-to-camhs/

**Comment by RhodesPeter** [comment]
I am closing this issue as we have completed the prototype and pitch. The link to the hosted site is also now on our README.
