### ISSUE TITLE
Prototype images

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#45]
![screen shot 2017-02-02 at 18 05 54](https://cloud.githubusercontent.com/assets/18164707/22561936/69951cf0-e972-11e6-8ad6-3c55248d8ce4.png)
![screen shot 2017-02-02 at 18 05 41](https://cloud.githubusercontent.com/assets/18164707/22561935/69952010-e972-11e6-9cbd-aabd66306a8f.png)
![screen shot 2017-02-02 at 18 06 05](https://cloud.githubusercontent.com/assets/18164707/22561933/69930384-e972-11e6-89b3-e01f18ede88c.png)
![screen shot 2017-02-02 at 18 06 26](https://cloud.githubusercontent.com/assets/18164707/22561932/6992315c-e972-11e6-93e1-3051545fb86c.png)
![screen shot 2017-02-02 at 18 06 34](https://cloud.githubusercontent.com/assets/18164707/22561934/69949e2e-e972-11e6-9312-dfb62d75a483.png)
![screen shot 2017-02-02 at 18 06 43](https://cloud.githubusercontent.com/assets/18164707/22561938/69aab916-e972-11e6-9883-1b2030e4b917.png)
![screen shot 2017-02-02 at 18 06 50](https://cloud.githubusercontent.com/assets/18164707/22561937/699743b8-e972-11e6-95e9-a39027f4c42c.png)

**Comment by Jasminpatel1** [comment]
Hello, I was wondering if there was any chance I could have the link to the app tody as I'm only in the hospita today and Wednesday. It was be good to have the user testing guide? Many thanks

**Comment by RhodesPeter** [comment]
Hi Jasmine, I have created an issue about testing [here](https://github.com/CYPIAPT-LNDSE/welcome-to-camhs/issues/46). I have added a link to the prototype in there.

**Comment by RhodesPeter** [comment]
I am closing this issue as we have completed the prototype and pitch.
