### ISSUE TITLE
Pitch event - Thursday 9th Feb - 5.30pm 

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#50]
We have some more information about the presentations on Thursday evening from Alex at Anna Freud:

A reminder about the Hackathon 3: Pitch Event this Thursday evening at Rodney Street.

Food and refreshments will be available from 5:30pm and each of the six teams will have 10mins to present their app and a panel will choose 2 apps to be developed further. The session will close soon after 7pm. As in previous hackathons, apps will be judged on a demonstration of the app alongside a presentation that covers:

- Implementation (how easily they can be brought into use in a service, or with young people/families)
- Technical viability (how easily the idea can be fully executed from a technical standpoint)
- Need (what is the need for the app)
- Evidence-base (what is the evidence base for the thing that the app does)
- Product ownership (who will be owning the product and can they make the time available)
- User Experience (UX) feedback (feedback gathered during the week between 2nd and 9th February)
- Product roadmap (plans for further development)

**Comment by RhodesPeter** [comment]
This issue builds upon these points for the presentation that I posted in the testing issue:

1. A description of the problem
2. Results of this week's testing
3. Their availability for the next month
4. A development plan (i.e. how are they going to ensure the product gets some traction)

**Comment by RhodesPeter** [comment]
@Jasminpatel1 How do you feel about the presentation? Can we help you with it at all?

**Comment by Jasminpatel1** [comment]
Hi, I'm feeling good. Just got some more really positive feedback (from children & young people who are service users and ex-service user and parents/carers. I've also received some feedback from consultant psychiatrists, family therapists, psychologists and the admin staff).  It obviously needs refinement but they all see a clear need for this. It would be great to run over the presentation with both of you, are you around earlier tomorrow?

**Comment by RhodesPeter** [comment]
Hi @Jasminpatel1, sounds great. 
I will be around for a phone call any time tomorrow so feel free to give me a ring 07833798916.

**Comment by RhodesPeter** [comment]
I am closing this issue as we have completed the pitch event 😀
