### ISSUE TITLE
PWA Google workshop stuff

### ISSUE THREAD

**Issue by nogainbar** [CYPIAPT-LNDSE/welcome-to-camhs#57]
Hey @RhodesPeter and @skibinska 

Since we mentioned maybe doing a PWA, I hope this can help, it is the link to the Google PWA workshop we had the good fortune to go to:

[PWA training resources](https://drive.google.com/drive/folders/0B9xlQg9XpugsNHhIWHFTbWhQTnM?usp=sharing)
Checkout especially the PDF titled- [progressive-web-apps-ilt-codelabs.pdf](https://drive.google.com/open?id=0B9xlQg9XpugsRDhVMGg4VDFOS2c) (the first one)

Also this is the [Codelabs](https://drive.google.com/open?id=0B9xlQg9XpugsNlFUYXRtRkdHelE) deck we worked from with zipped code and exercises.

If these links dont work for some reason, let me know and il just invite you on the google drive if you send me your email. :)

**Comment by RhodesPeter** [comment]
I am closing this issue as we have decided against creating a PWA. Relates to conversations we have had on issue #67.
