### ISSUE TITLE
Animate SVGs with GSAP

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#72]
All illustrations should have animation where possible. 

Leaves gently blowing in the wind, tails wagging, balloons bobbing.

**Comment by MHemsley** [comment]
I think this should be pushed to the next sprint, as I definitely see it as a nice to have instead of essential. Getting the structure and base code right should be the main priority for the first spring

**Comment by RhodesPeter** [comment]
Ok no problem @MHemsley. I will remove this from sprint 1.

**Comment by RhodesPeter** [comment]
I am closing this issue as we have added all of the animation that we are intending to use for sprint 2. On the advice of Noga we used Anime.js instead of GSAP.
