### ISSUE TITLE
Ask Jasmin to create a survey on Survey Monkey

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#73]
Ask Jasmin to create a survey on Survey Monkey which we will add to the project for testing at the end of sprint 1.

**Comment by skibinska** [comment]
Are still need it?

**Comment by skibinska** [comment]
Do we still need it?

**Comment by RhodesPeter** [comment]
I have closed this issue as sprint 1 has finished.
