### ISSUE TITLE
Define data flow/PWA storage

### ISSUE THREAD

**Issue by MHemsley** [CYPIAPT-LNDSE/welcome-to-camhs#75]
Task to discuss the implementation of data flow/local storage of answers (and any other data).

It would be good to have an idea where your current thinking of this is? There are a few data security/privacy elements it would be good to ensure that we've thought through

**Comment by RhodesPeter** [comment]
I am researching our options for storing the data collected on the questionnaire.  

- Here is an article on how secure session storage is --> https://blog.guya.net/2015/08/25/the-never-ending-browser-sessions/

**Comment by RhodesPeter** [comment]
![screen shot 2017-03-07 at 11 46 52](https://cloud.githubusercontent.com/assets/18164707/23655165/d48f6ff6-032b-11e7-9ea4-bbe836be7e6a.png)

**Comment by RhodesPeter** [comment]
It can be done with session storage on the browser and we can clear this data at the end of the session (when someone emails the PDF/CSV). 

This is how it could be done --> http://blog.teamtreehouse.com/storing-data-on-the-client-with-localstorage. 

Is this safe enough for the data added to the questionnaire?

**Comment by RhodesPeter** [comment]
I am closing this issue as we have decided to use sessionStorage.
