### ISSUE TITLE
Sprint retrospective

### ISSUE THREAD

**Issue by MHemsley** [CYPIAPT-LNDSE/welcome-to-camhs#89]
Hi all,

It would be good to get a time in to have a sprint retro towards the end of this week (Friday morning?)

The purpose of this will be to cover the broad points:
What went well during this sprint?
What could have been done better during the sprint?
What additional support would have been helpful?
What could we do differently to improve?

This process should not be accusational, but should facilitate communication to improve team effectiveness within the next sprint, and to facilitate personal development.

**Comment by bradreeder** [comment]
Hi @MHemsley, I'm going to be away in Sussex this Friday. I'd be available to do retrospectives on Monday next week (or thursday). I think this team scheduled that Monday as the last day of this sprint but I will leave it to @RhodesPeter & @skibinska 's preference.

**Comment by RhodesPeter** [comment]
@MHemsley @bradreeder @skibinska - Tuesday would be ideal for me and Ewelina.

**Comment by MHemsley** [comment]
I'm away next week, but happy for @bradreeder to lead and report back on my return

**Comment by RhodesPeter** [comment]
I am closing this issue as we completed the sprint 1 retrospective on Friday 24th March.
